import React from 'react';
import './ModelResponsePage.css';

const ModelResponsePage = () => {
  return (
    <div className="response-container">
      <h2>Model Output</h2>
      <p>This is a static response generated by the AI based on user query.</p>
    </div>
  );
};

export default ModelResponsePage;
